app_link:
    resource: "@AppBundle/Resources/config/routing/link.yml"
    prefix:   /link

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_homepage_link:
    path:     /{id}
    defaults: { _controller: AppBundle:Default:indexSince }
    requirements:
        id: \d*
